# Generated by Django 3.0.6 on 2022-05-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_date',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_date',
            new_name='startdate',
        ),
    ]
